[project]
name = "250400-bowldi-paper"
version = "0.1.0"
description = "Project to follow the BOWLDI paper"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentspeak>=0.2.2",
    "owlready2>=0.47",
    "spade==4.0.2",
    "spade-bdi>=0.3.2",
]
